config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :miniblogs do
    # collection do
      post :confirm, on: :collection
    # end
  end

  root to: 'miniblogs#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/miniblog.rb
class Miniblog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/miniblogs_controller.rb
class MiniblogsController < ApplicationController
   before_action :set_blog, only:[:show, :edit, :update, :destroy]

   def index
     @miniblogs = Miniblog.all
   end

   def new
     if params[:back]
          Miniblog.new(blog_param)
     else
         @miniblog = Miniblog.new
     end
   end

   def create
     @miniblog = Miniblog.new(blog_param)

     if @miniblog.save
       redirect_to miniblogs_path, notice:"投稿しました！"
     else
       render 'new'
     end

   end

   def show
   end

   def edit
   end

   def update
     if @miniblog.update(blog_param)
       redirect_to miniblogs_path, notice:"更新しました！"
     else
       render 'edit'
     end
   end

   def destroy
       @miniblog.destroy
       redirect_to miniblogs_path, notice:"削除しました！"
   end

   def confirm
     @miniblog = Miniblog.new(blog_param)
     render :new  if @miniblog.invalid?
   end

   private

   def set_blog
     @miniblog = Miniblog.find(params[:id])
   end

   def blog_param
     params.require(:miniblog).permit(:title,:content)
   end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/miniblogs_helper.rb
module MiniblogsHelper

  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_miniblogs_path
    elsif action_name == 'edit'
      miniblog_path
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/miniblogs/_form.html.erb
<%= form_with(model: @miniblog, local: true, url: choose_new_or_edit) do |form| %>
  <!-- エラー表示 -->
  <% if @miniblog.errors.any? %>
     <div id = "error_explanation">
       <h2><%= @miniblog.errors.count %>件のエラー</h2>
       <ul>

         <% @miniblog.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>

       </ul>
     </div>
  <% end %>


   <div class="blog_title">
     <%= form.label :title %>
     <%= form.text_field :title %>
   </div>

   <div class="blog_content">
     <%= form.label :content %>
     <%= form.text_field :content %>
   </div>

   <%= form.submit "完了" %>

<% end %>

<br>

<%= link_to "一覧に戻る", miniblogs_path %>

app/views/miniblogs/confirm.erb
<h1>この内容で投稿する</h1>

<%= form_with(model: @miniblog, local: true, url: miniblogs_path) do |form| %>
   <%= form.hidden_field  :title %>
   <%= form.hidden_field  :content %>

   <p>タイトル:<%= @miniblog.title %></p>
   <p>本文:<%= @miniblog.content %></p>
   <%= form.submit "登録する" %>

<% end %>

app/views/miniblogs/edit.erb
<h2>ブログを編集</h2>

<%= render 'form' %>

app/views/miniblogs/index.erb
<h1>一覧</h1>

<%= notice %>

<table>
  <tr>
    <th>タイトル</th>
  </tr>

  <% @miniblogs.each do |miniblog| %>
    <tr>
      <td class="title"><%= miniblog.title %></td>
      <!-- <td><%= miniblog.content %></td> -->
      <td><%= link_to '詳細', miniblog_path(miniblog.id) %></td>
      <td><%= link_to "編集", edit_miniblog_path(miniblog.id) %></td>
      <td><%= link_to '削除', miniblog_path(miniblog.id), method: :delete,
      data:{confirm:'このブログを削除してよろしいですか？'} %></td>
    </tr>
  <% end %>

</table>

<br>

<%= link_to '新規投稿', new_miniblog_path %>

app/views/miniblogs/new.erb
<h2>ブログを作成</h2>

<%= render 'form' %>

app/views/miniblogs/show.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @miniblog.title %></p>
<p>内容: <%= @miniblog.content %></p>

<%= link_to "一覧に戻る", miniblogs_path %>